name: fortify-ci-tools FoD scan

on: 
  workflow_dispatch:
  
jobs:
  FoD-SAST-Scan:
    runs-on: ubuntu-latest

    steps:
      - name: Check Out Source Code
        uses: actions/checkout@v2
      
      - name: Package Code + Dependencies
        uses: docker://fortifydocker/fortify-ci-tools:latest
        with:
          entrypoint: scancentral
          args: package -bt mvn -o package.zip
      
      - name: Upload package and start scan
        uses: docker://fortifydocker/fortify-ci-tools:latest
        with:
          entrypoint: FoDUpload 
          args: -z package.zip -aurl ${{env.FOD_AURL}} -purl ${{env.FOD_PURL}} -rid ${{env.FOD_RELEASE_ID}} -tc ${{env.FOD_TENANT}} -uc ${{env.FOD_USER}} ${{env.FOD_PAT}} ${{env.FOD_UPLOADER_OPTS}}
        env: 
          FOD_AURL: https://api.emea.fortify.com
          FOD_PURL: https://emea.fortify.com
          FOD_TENANT: emeademo
          FOD_USER: dave_h
          FOD_PAT: TXgwSkk_UlVpdSk5c3BQNHIwKDBMTnBMenJDcGlS0
          FOD_RELEASE_ID: 111547
          FOD_UPLOADER_OPTS: "-ep 2 -pp 0 -I 1 -apf"
